version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: feefo_reviews
        description: "Raw Feefo reviews from API"
        columns:
          - name: url
            description: "Unique review URL (primary key)"
            tests:
              - not_null
              - unique

      - name: feefo_reviews__products
        description: "Nested product reviews from within service reviews"
        columns:
          - name: product__sku
            description: "Product SKU"
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: ref('stg_feefo_product_ratings')
                    field: product_sku
                  config:
                    severity: warn  # Warn because not all reviewed SKUs may have ratings
          - name: product__title
            description: "Product title"
          - name: rating__rating
            description: "Product review rating (1-5)"
            tests:
              - accepted_values:
                  arguments:
                    values: [1, 2, 3, 4, 5]
                    quote: false
          - name: _dlt_parent_id
            description: "DLT parent ID linking to feefo_reviews._dlt_id"
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('bronze', 'feefo_reviews')
                    field: _dlt_id

      - name: feefo_products_for_reviews
        description: "Product ratings for SKUs found in reviews"
        columns:
          - name: sku
            description: "Product SKU (primary key)"
            tests:
              - not_null
              - unique

models:
  - name: stg_feefo_reviews
    description: "Staging view for Feefo reviews with nullable field handling"
    columns:
      - name: review_id
        description: "Unique review identifier (url)"
        tests:
          - not_null
          - unique
      - name: merchant_id
        description: "Merchant identifier (COALESCE default: 'unknown')"
        tests:
          - not_null
      - name: service_id
        description: "Service ID (nullable - may be missing for some review types)"
      - name: service_rating
        description: "Service rating 1-5 (nullable - some reviews have no rating)"
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
                quote: false
      - name: rating_min
        description: "Minimum rating value (COALESCE default: 1)"
        tests:
          - not_null
      - name: rating_max
        description: "Maximum rating value (COALESCE default: 5)"
        tests:
          - not_null
      - name: moderation_status
        description: "Moderation status (COALESCE default: 'unmoderated')"
        tests:
          - not_null
      - name: verification_state
        description: "Feedback verification state (COALESCE default: 'unverified')"
        tests:
          - not_null
      - name: created_at
        description: "Review creation timestamp (nullable - may be missing for legacy data)"
      - name: helpful_votes
        description: "Number of helpful votes (COALESCE default: 0)"
        tests:
          - not_null
      - name: locale
        description: "Locale/language code (COALESCE default: 'en_GB')"
        tests:
          - not_null
      - name: last_updated_date
        description: "Last updated timestamp (nullable)"

  - name: stg_feefo_product_ratings
    description: "Staging view for Feefo product ratings"
    columns:
      - name: product_sku
        description: "Product SKU"
        tests:
          - not_null
          - unique
      - name: product_rating
        description: "Product rating (decimal, 1.0-5.0)"
      - name: merchant_id
        description: "Merchant identifier"
        tests:
          - not_null
